### PR TITLE
Update conjugation.txt

### PR DESCRIPTION
**Pull request by Konstantin-Glukhov**
Corrected spelling

### CODE REVIEW

**Comment by Pomax** [comment]
These tables were correct. Welcome to legacy verb forms.

See http://dictionary.goo.ne.jp/jn/151501/meaning/m0u/%E3%81%A7%E3%81%99/ and http://dictionary.goo.ne.jp/jn/208067/meaning/m0u/%E3%81%BE%E3%81%99/

**Comment by Konstantin-Glukhov** [comment]
A little bit confused by the comment. The provided links are the ones that were consulted before making corrections. They show でしょ and ましょ but not でしよ and ましよ. In addition the comment to Issue #13 indicates the agreement to でしょ correction.

**Comment by Pomax** [comment]
Hm, it looks like I was mislead by the typesetting. I will reopen the PRs for the corrections.

**Comment by Konstantin-Glukhov** [comment]
Try Meiryo, in my opinion the best modern Japanese typeface, and I am not a Microsoft fan but I had to admit they did a good job with it.

**Comment by Pomax** [comment]
I like Meiryo, but I particularly like Kozuka Mincho (which comes with most Adobe suite programs). The actual book is typeset in Palatino Linotype and Kozuka Mincho (for the most part) with nice and clear typographic distinction while keeping a good serif look.

**Pull request merged**
